apiVersion: v1
kind: PersistentVolume
metadata:
  name: rate-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: rate-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: rate-disk
    fsType: ext4
