apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-rate
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
        - command:
            - rate
          env:
            - name: DLOG
              value: DEBUG
          image: teresaliuchang/hotel_demo:v1.7
          name: hotel-reserv-rate
          ports:
            - name: h2c
              containerPort: 8084
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 16
