apiVersion: v1
kind: PersistentVolume
metadata:
  name: recommendation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: recommendation-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: recommendation-disk
    fsType: ext4
