default:
    just --list
    
deploy_and_init: deploy init_social_graph
    
deploy:
    docker stack deploy --compose-file=docker-compose-mimetic.yml social_network
    
undeploy:
    docker stack rm social_network
    
init_social_graph:
    python3 scripts/init_social_graph.py --graph=socfb-Reed98

get_jaeger_services:
    curl -sX 'GET' \
        'http://0.0.0.0:16686/api/services' \
        -H 'accept: application/json'

get_jaeger_traces service lookback_secs limit:
    curl -sX 'GET' \
        'http://0.0.0.0:16686/api/traces?service={{service}}&lookback={{lookback_secs}}000&limit={{limit}}' \
        -H 'accept: application/json'

compose rps duration_secs:
    ../wrk2/wrk -D exp -t 10 -c 10 -d {{duration_secs}} -L -s \
        ./wrk2/scripts/social-network/compose-post.lua \
        http://0.0.0.0:8080/wrk2-api/post/compose \
        -R {{rps}}
