apiVersion: v1
kind: PersistentVolume
metadata:
  name: geo-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: geo-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: geo-disk
    fsType: ext4
