apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: reservation-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: reservation-disk
    fsType: ext4
