apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: user-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: user-disk
    fsType: ext4
