rpiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-client
  labels:
    app: hr-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-client
  template:
    metadata:
      labels:
        app: hr-client
      name: hr-client
    spec:
      containers:
        - name: hr-client
          image: deathstarbench/wrk2-client
          command: ["/bin/sh"]
          args:
            - -c
            - sleep 365d
          imagePullPolicy: Always
      restartPolicy: Always
